// 自动生成，勿手改。来源: scripts/perfumes.csv
// 重新生成: npm run import:perfumes
import type { Perfume } from "./data";

export const PERFUMES_EXTRA: Record<string, Perfume> = {
  "蓝风铃": {
    id: "蓝风铃",
    name: "蓝风铃",
    brand: "Jo Malone",
    brandCn: "祖玛珑",
    notes: {
      top: ["风铃草"],
      heart: ["柿子","小苍兰"],
      base: ["白麝香"],
    },
    intensity: 2,
    longevity: 2,
    tier: "advanced",
    priceRange: "¥650/30ml",
    description: "清透风铃草与柿子的水感花香，日常百搭",
  },
  "英国梨与小苍兰": {
    id: "英国梨与小苍兰",
    name: "英国梨与小苍兰",
    brand: "Jo Malone",
    brandCn: "祖玛珑",
    notes: {
      top: ["梨"],
      heart: ["小苍兰","玫瑰"],
      base: ["广藿香","麝香"],
    },
    intensity: 2,
    longevity: 3,
    tier: "advanced",
    priceRange: "¥650/30ml",
    description: "清甜梨香叠小苍兰，温柔易亲近的入门香",
  },
  "碧海蓝": {
    id: "碧海蓝",
    name: "碧海蓝",
    brand: "Acqua di Parma",
    brandCn: "帕尔玛之水",
    notes: {
      top: ["香橙","海盐","柠檬"],
      heart: ["海风","迷迭香","薰衣草"],
      base: ["雪松","麝香"],
    },
    intensity: 2,
    longevity: 2,
    tier: "advanced",
    priceRange: "¥500-800/50ml",
    description: "地中海蓝风，清透海盐与香橙的夏日水感",
  },
  "光晕": {
    id: "光晕",
    name: "光晕",
    brand: "Lancome",
    brandCn: "兰蔻",
    notes: {
      top: ["梨","香橙"],
      heart: ["玫瑰","茉莉","牡丹"],
      base: ["雪松","麝香","香草"],
    },
    intensity: 3,
    longevity: 3,
    tier: "advanced",
    priceRange: "¥600-900/30ml",
    description: "温柔日常的花果香，通勤约会不出错",
  },
  "雨后花园": {
    id: "雨后花园",
    name: "雨后花园",
    brand: "Hermes",
    brandCn: "爱马仕",
    notes: {
      top: ["葡萄柚","香橙"],
      heart: ["莲花","风信子","绿叶"],
      base: ["木质","乳香","麝香"],
    },
    intensity: 2,
    longevity: 3,
    tier: "advanced",
    priceRange: "¥800-1200/50ml",
    description: "尼罗河花园的清透水感，莲叶与阳光的交织",
  },
  "流浪者之歌": {
    id: "流浪者之歌",
    name: "流浪者之歌",
    brand: "Byredo",
    brandCn: "百瑞德",
    notes: {
      top: ["柠檬","胡椒"],
      heart: ["焚香","鸢尾"],
      base: ["琥珀","檀木","麝香"],
    },
    intensity: 3,
    longevity: 3,
    tier: "signature",
    priceRange: "¥1200-1600/50ml",
    description: "Gypsy Water 柠檬松针的冷绿意境",
  },
  "水中影": {
    id: "水中影",
    name: "水中影",
    brand: "Diptyque",
    brandCn: "蒂普提克",
    notes: {
      top: ["黑醋栗叶","绿叶"],
      heart: ["玫瑰","无花果"],
      base: ["木质","麝香"],
    },
    intensity: 3,
    longevity: 3,
    tier: "advanced",
    priceRange: "¥700-1100/50ml",
    description: "绿意玫瑰，黑醋栗叶的清冷绿意与湿漉花香",
  },
  "冷水": {
    id: "冷水",
    name: "冷水",
    brand: "Davidoff",
    brandCn: "大卫杜夫",
    notes: {
      top: ["海盐","薄荷","薰衣草"],
      heart: ["迷迭香","鼠尾草"],
      base: ["雪松","麝香","琥珀"],
    },
    intensity: 3,
    longevity: 3,
    tier: "budget",
    priceRange: "¥200-400/100ml",
    description: "经典水生调，平价清爽的入门冷水",
  },
  "光影": {
    id: "光影",
    name: "光影",
    brand: "Dolce & Gabbana",
    brandCn: "杜嘉班纳",
    notes: {
      top: ["柠檬","青苹果","梨"],
      heart: ["茉莉","玫瑰","薰衣草"],
      base: ["雪松","琥珀","麝香"],
    },
    intensity: 2,
    longevity: 2,
    tier: "advanced",
    priceRange: "¥300-500/50ml",
    description: "Light Blue 的地中海清新，阳光与柑橘的假日",
  },
  "白苔": {
    id: "白苔",
    name: "白苔",
    brand: "Acca Kappa",
    brandCn: "艾克卡帕",
    notes: {
      top: ["柠檬","佛手柑"],
      heart: ["薰衣草","迷迭香"],
      base: ["麝香","琥珀","雪松"],
    },
    intensity: 1,
    longevity: 1,
    tier: "advanced",
    priceRange: "¥200-350/50ml",
    description: "洁净皂感的白麝香，伪体香的经典代表",
  },
  "白茶-祖玛珑": {
    id: "白茶-祖玛珑",
    name: "白茶",
    brand: "Jo Malone",
    brandCn: "祖玛珑",
    notes: {
      top: ["茶叶","佛手柑"],
      heart: ["白茶","茉莉"],
      base: ["麝香","木质"],
    },
    intensity: 1,
    longevity: 1,
    tier: "advanced",
    priceRange: "¥500-800/30ml",
    description: "清雅的茶香叠白麝香，安静的书卷气质",
  },
  "暖暖椰奶": {
    id: "暖暖椰奶",
    name: "暖暖椰奶",
    brand: "Tom Ford",
    brandCn: "汤姆·福特",
    notes: {
      top: ["柠檬","香橙","佛手柑"],
      heart: ["椰奶","橙花"],
      base: ["琥珀","麝香"],
    },
    intensity: 3,
    longevity: 3,
    tier: "signature",
    priceRange: "¥1200-1800/50ml",
    description: "Soleil Blanc 的假日暖阳，椰香白花与琥珀的慵懒",
  },
  "真我": {
    id: "真我",
    name: "真我",
    brand: "Dior",
    brandCn: "迪奥",
    notes: {
      top: ["木兰","香橙"],
      heart: ["玫瑰","茉莉","桂花"],
      base: ["木质","麝香"],
    },
    intensity: 3,
    longevity: 3,
    tier: "advanced",
    priceRange: "¥800-1300/50ml",
    description: "Jadore 的华丽花香，金色水滴般璀璨的熟女气质",
  },
  "可可小姐": {
    id: "可可小姐",
    name: "可可小姐",
    brand: "Chanel",
    brandCn: "香奈儿",
    notes: {
      top: ["橙","葡萄柚"],
      heart: ["玫瑰","茉莉","薰衣草"],
      base: ["广藿香","香草","麝香"],
    },
    intensity: 3,
    longevity: 4,
    tier: "advanced",
    priceRange: "¥1000-1500/50ml",
    description: "Coco Mademoiselle 独立自信的现代女性香",
  },
  "花悦": {
    id: "花悦",
    name: "花悦",
    brand: "Dior",
    brandCn: "迪奥",
    notes: {
      top: ["柑橘","牡丹"],
      heart: ["玫瑰","铃兰"],
      base: ["麝香","雪松"],
    },
    intensity: 2,
    longevity: 2,
    tier: "advanced",
    priceRange: "¥700-1100/50ml",
    description: "Miss Dior Blooming Bouquet 少女感的花束气息",
  },
  "黑鸦片": {
    id: "黑鸦片",
    name: "黑鸦片",
    brand: "YSL",
    brandCn: "圣罗兰",
    notes: {
      top: ["梨","咖啡"],
      heart: ["玫瑰","茉莉","橙花"],
      base: ["香草","焦糖","广藿香"],
    },
    intensity: 4,
    longevity: 4,
    tier: "advanced",
    priceRange: "¥800-1200/50ml",
    description: "Black Opium 甜酷的咖啡花香，夜店女王香",
  },
  "好事成双": {
    id: "好事成双",
    name: "好事成双",
    brand: "Lancome",
    brandCn: "兰蔻",
    notes: {
      top: ["黑加仑","梨"],
      heart: ["鸢尾","茉莉","玫瑰"],
      base: ["香草","焦糖","广藿香"],
    },
    intensity: 4,
    longevity: 4,
    tier: "advanced",
    priceRange: "¥800-1200/50ml",
    description: "La Vie Est Belle 甜蜜鸢尾与美食调的人气经典",
  },
  "花之秘境": {
    id: "花之秘境",
    name: "花之秘境",
    brand: "Givenchy",
    brandCn: "纪梵希",
    notes: {
      top: ["梨","橙"],
      heart: ["橙花","茉莉","玫瑰"],
      base: ["香草","琥珀","麝香"],
    },
    intensity: 3,
    longevity: 3,
    tier: "advanced",
    priceRange: "¥600-1000/50ml",
    description: "LInterdit 禁忌之花的橙花茉莉，优雅而温柔",
  },
  "克洛伊": {
    id: "克洛伊",
    name: "克洛伊",
    brand: "Chloe",
    brandCn: "蔻依",
    notes: {
      top: ["牡丹","荔枝"],
      heart: ["玫瑰","木兰"],
      base: ["雪松","琥珀","麝香"],
    },
    intensity: 2,
    longevity: 2,
    tier: "advanced",
    priceRange: "¥600-900/50ml",
    description: "Chloe EDP 温柔小女人的玫瑰花香",
  },
  "爱情故事": {
    id: "爱情故事",
    name: "爱情故事",
    brand: "Chloe",
    brandCn: "蔻依",
    notes: {
      top: ["橙花油","柠檬"],
      heart: ["茉莉","玫瑰"],
      base: ["雪松","木质"],
    },
    intensity: 2,
    longevity: 2,
    tier: "advanced",
    priceRange: "¥600-900/50ml",
    description: "Love Story 橙花与茉莉的缠绵，浪漫约会香",
  },
  "花宫娜": {
    id: "花宫娜",
    name: "花宫娜",
    brand: "Fragonard",
    brandCn: "花宫娜",
    notes: {
      top: ["橙","柠檬"],
      heart: ["玫瑰","茉莉","百合"],
      base: ["麝香","檀香"],
    },
    intensity: 2,
    longevity: 2,
    tier: "advanced",
    priceRange: "¥200-400/50ml",
    description: "法国老牌格拉斯玫瑰，平价入门的花香代表",
  },
  "紫丁香": {
    id: "紫丁香",
    name: "紫丁香",
    brand: "Demeter",
    brandCn: "帝门特",
    notes: {
      top: ["紫丁香"],
      heart: ["铃兰","风信子"],
      base: ["麝香","木质"],
    },
    intensity: 1,
    longevity: 1,
    tier: "budget",
    priceRange: "¥100-200/30ml",
    description: "单一紫丁香，还原雨后的清透花香",
  },
  "乌木沉香": {
    id: "乌木沉香",
    name: "乌木沉香",
    brand: "Tom Ford",
    brandCn: "汤姆·福特",
    notes: {
      top: ["沉香","檀木"],
      heart: ["小豆蔻","胡椒"],
      base: ["琥珀","焚香","麝香"],
    },
    intensity: 4,
    longevity: 5,
    tier: "signature",
    priceRange: "¥1800-2500/50ml",
    description: "Oud Wood 高级感乌木与檀香的完美融合",
  },
  "墨恋": {
    id: "墨恋",
    name: "墨恋",
    brand: "Lalique",
    brandCn: "莱俪",
    notes: {
      top: ["柏木","香根草"],
      heart: ["广藿香"],
      base: ["檀香","麝香"],
    },
    intensity: 3,
    longevity: 3,
    tier: "advanced",
    priceRange: "¥200-350/100ml",
    description: "Encre Noire 暗黑木质调，墨香与雨湿森林的意象",
  },
  "冥府之路": {
    id: "冥府之路",
    name: "冥府之路",
    brand: "Diptyque",
    brandCn: "蒂普提克",
    notes: {
      top: ["焚香","木烟"],
      heart: ["玫瑰","姜"],
      base: ["檀香","雪松","麝香"],
    },
    intensity: 2,
    longevity: 3,
    tier: "advanced",
    priceRange: "¥700-1100/50ml",
    description: "幽冷焚香木质，教堂仪式感的阴郁禅意",
  },
  "灰烬": {
    id: "灰烬",
    name: "灰烬",
    brand: "Byredo",
    brandCn: "百瑞德",
    notes: {
      top: ["焚香","姜"],
      heart: ["皮革","雪松"],
      base: ["琥珀","檀木","麝香"],
    },
    intensity: 3,
    longevity: 3,
    tier: "signature",
    priceRange: "¥1200-1600/50ml",
    description: "Accord Oud 焚香辛辣木质，暗夜行走的力量感",
  },
  "墨水-川久保玲": {
    id: "墨水-川久保玲",
    name: "墨水",
    brand: "Comme des Garcons",
    brandCn: "川久保玲",
    notes: {
      top: ["柏木","雪松"],
      heart: ["焚香","香根草"],
      base: ["麝香","琥珀"],
    },
    intensity: 3,
    longevity: 3,
    tier: "advanced",
    priceRange: "¥500-800/50ml",
    description: "Wonderwood 扩香极好的干燥木屑与焚香",
  },
  "一千零一夜": {
    id: "一千零一夜",
    name: "一千零一夜",
    brand: "Guerlain",
    brandCn: "娇兰",
    notes: {
      top: ["柠檬","香橙"],
      heart: ["玫瑰","鸢尾"],
      base: ["香草","劳丹脂","麝香"],
    },
    intensity: 4,
    longevity: 4,
    tier: "advanced",
    priceRange: "¥900-1400/50ml",
    description: "Shalimar 百年经典东方香，香草琥珀的性感传奇",
  },
  "琥珀君王": {
    id: "琥珀君王",
    name: "琥珀君王",
    brand: "Serge Lutens",
    brandCn: "芦丹氏",
    notes: {
      top: ["檀木","香草"],
      heart: ["琥珀","没药"],
      base: ["树脂","雪松","麝香"],
    },
    intensity: 4,
    longevity: 5,
    tier: "signature",
    priceRange: "¥800-1300/50ml",
    description: "Ambre Sultan 浓郁琥珀树脂，暖甜奢华的东方丰碑",
  },
  "华丽之夜": {
    id: "华丽之夜",
    name: "华丽之夜",
    brand: "YSL",
    brandCn: "圣罗兰",
    notes: {
      top: ["柑橘","姜"],
      heart: ["肉桂","茉莉"],
      base: ["没药","乳香","麝香"],
    },
    intensity: 4,
    longevity: 4,
    tier: "advanced",
    priceRange: "¥700-1100/50ml",
    description: "Opium 经典辛香东方调，八十年代权力感的代表",
  },
  "沙漠孤烟": {
    id: "沙漠孤烟",
    name: "沙漠孤烟",
    brand: "Tauer",
    brandCn: "陶尔",
    notes: {
      top: ["孜然","香草根"],
      heart: ["琥珀","雪松"],
      base: ["香草","麝香","焚香"],
    },
    intensity: 3,
    longevity: 4,
    tier: "signature",
    priceRange: "¥900-1400/50ml",
    description: "L Air du Desert Marocain 辛香琥珀的沙漠之夜",
  },
  "极致琥珀": {
    id: "极致琥珀",
    name: "极致琥珀",
    brand: "Maison Francis Kurkdjian",
    brandCn: "MFK",
    notes: {
      top: ["琥珀","劳丹脂"],
      heart: ["安息香","香草"],
      base: ["树脂","麝香"],
    },
    intensity: 3,
    longevity: 4,
    tier: "signature",
    priceRange: "¥1500-2200/70ml",
    description: "Grand Soir 热烈琥珀配香草，聚会气场之王",
  },
  "烟草香草": {
    id: "烟草香草",
    name: "烟草香草",
    brand: "Tom Ford",
    brandCn: "汤姆·福特",
    notes: {
      top: ["烟草","辛料"],
      heart: ["香草","可可"],
      base: ["琥珀","麝香","檀木"],
    },
    intensity: 4,
    longevity: 4,
    tier: "signature",
    priceRange: "¥1500-2200/50ml",
    description: "Tobacco Vanille 烟熏甜暖，秋冬质感香的代表",
  },
  "红香": {
    id: "红香",
    name: "红香",
    brand: "Cartier",
    brandCn: "卡地亚",
    notes: {
      top: ["橙","姜"],
      heart: ["玫瑰","丁香"],
      base: ["檀香","麝香","琥珀"],
    },
    intensity: 3,
    longevity: 3,
    tier: "advanced",
    priceRange: "¥600-1000/50ml",
    description: "经典辛香东方调，温暖香料与檀木的微醺感",
  },
  "罂粟": {
    id: "罂粟",
    name: "罂粟",
    brand: "YSL",
    brandCn: "圣罗兰",
    notes: {
      top: ["姜","胡椒"],
      heart: ["肉桂","烟草"],
      base: ["皮革","琥珀"],
    },
    intensity: 4,
    longevity: 4,
    tier: "advanced",
    priceRange: "¥700-1200/50ml",
    description: "辛辣皮革调，不羁的暗黑质感",
  },
  "香道": {
    id: "香道",
    name: "香道",
    brand: "Comme des Garcons",
    brandCn: "川久保玲",
    notes: {
      top: ["焚香","木烟"],
      heart: ["沉香","檀木"],
      base: ["琥珀","麝香"],
    },
    intensity: 3,
    longevity: 4,
    tier: "advanced",
    priceRange: "¥600-1000/50ml",
    description: "焚香木质线，肃穆的寺庙感与冥想氛围",
  },
  "壁炉火光": {
    id: "壁炉火光",
    name: "壁炉火光",
    brand: "Maison Margiela",
    brandCn: "梅森·马吉拉",
    notes: {
      top: ["焚香","胡椒"],
      heart: ["薰衣草","木质"],
      base: ["琥珀","雪松"],
    },
    intensity: 3,
    longevity: 3,
    tier: "advanced",
    priceRange: "¥700-1100/100ml",
    description: "By the Fireplace 燃烧木头的温暖与甜意",
  },
  "天使": {
    id: "天使",
    name: "天使",
    brand: "Thierry Mugler",
    brandCn: "穆格勒",
    notes: {
      top: ["棉花糖","蜂蜜"],
      heart: ["黑加仑","巧克力"],
      base: ["焦糖","麝香","香草"],
    },
    intensity: 4,
    longevity: 5,
    tier: "advanced",
    priceRange: "¥600-1000/50ml",
    description: "Angel 现代美食调的鼻祖，棉花糖与巧克力的甜疯",
  },
  "毒药": {
    id: "毒药",
    name: "毒药",
    brand: "Dior",
    brandCn: "迪奥",
    notes: {
      top: ["杏仁","香草"],
      heart: ["茉莉","玫瑰"],
      base: ["檀木","可可","麝香"],
    },
    intensity: 4,
    longevity: 4,
    tier: "advanced",
    priceRange: "¥700-1100/50ml",
    description: "Hypnotic Poison 杏仁香草的温暖毒药，甜而不腻",
  },
  "粉色甜品": {
    id: "粉色甜品",
    name: "粉色甜品",
    brand: "Aquolina",
    brandCn: "阿奎莉娜",
    notes: {
      top: ["棉花糖","糖"],
      heart: ["草莓","覆盆子"],
      base: ["焦糖","香草","麝香"],
    },
    intensity: 3,
    longevity: 3,
    tier: "budget",
    priceRange: "¥100-200/100ml",
    description: "Pink Sugar 极甜少女香，平价棉花糖炸弹",
  },
  "初恋": {
    id: "初恋",
    name: "初恋",
    brand: "Kilian",
    brandCn: "凯利安",
    notes: {
      top: ["棉花糖","橙花"],
      heart: ["茉莉","蜂蜜"],
      base: ["糖","麝香"],
    },
    intensity: 4,
    longevity: 4,
    tier: "signature",
    priceRange: "¥1500-2200/50ml",
    description: "Love Dont Be Shy 甜橙花与棉花糖，甜度爆表的情人节香",
  },
  "黑幽灵": {
    id: "黑幽灵",
    name: "黑幽灵",
    brand: "Kilian",
    brandCn: "凯利安",
    notes: {
      top: ["朗姆","咖啡"],
      heart: ["焦糖","糖"],
      base: ["杏仁","檀木"],
    },
    intensity: 4,
    longevity: 4,
    tier: "signature",
    priceRange: "¥1500-2200/50ml",
    description: "Black Phantom 朗姆咖啡的暗黑美食调，又甜又酷",
  },
  "蜂蜜乌木": {
    id: "蜂蜜乌木",
    name: "蜂蜜乌木",
    brand: "Roja Parfums",
    brandCn: "罗嘉",
    notes: {
      top: ["蜂蜜","茉莉"],
      heart: ["玫瑰","肉桂"],
      base: ["沉香","香草","琥珀"],
    },
    intensity: 4,
    longevity: 5,
    tier: "signature",
    priceRange: "¥2000-3500/50ml",
    description: "重度琥珀蜂蜜与乌木，极致奢华的甜暖",
  },
  "巧克力梦": {
    id: "巧克力梦",
    name: "巧克力梦",
    brand: "Montale",
    brandCn: "蒙塔莱",
    notes: {
      top: ["可可","香草"],
      heart: ["咖啡","玫瑰"],
      base: ["琥珀","麝香"],
    },
    intensity: 4,
    longevity: 4,
    tier: "advanced",
    priceRange: "¥500-800/50ml",
    description: "浓郁巧克力美食调，甜的深渊单香成瘾",
  },
  "牛奶": {
    id: "牛奶",
    name: "牛奶",
    brand: "Commodity",
    brandCn: "科摩蒂",
    notes: {
      top: ["牛奶","糖"],
      heart: ["椰子"],
      base: ["檀木","琥珀"],
    },
    intensity: 2,
    longevity: 3,
    tier: "advanced",
    priceRange: "¥500-800/100ml",
    description: "Milk 暖甜椰奶檀木，拥抱感的舒适美食调",
  },
  "白晶": {
    id: "白晶",
    name: "白晶",
    brand: "Bvlgari",
    brandCn: "宝格丽",
    notes: {
      top: ["荔枝","梨"],
      heart: ["莲花","茉莉"],
      base: ["雪松","麝香"],
    },
    intensity: 2,
    longevity: 2,
    tier: "advanced",
    priceRange: "¥500-800/40ml",
    description: "Omnia Crystalline 清甜荔枝水汽，夏日淡雅白花香",
  },
  "安娜苏": {
    id: "安娜苏",
    name: "安娜苏",
    brand: "Anna Sui",
    brandCn: "安娜苏",
    notes: {
      top: ["草莓","苹果"],
      heart: ["玫瑰","牡丹"],
      base: ["香草","麝香","雪松"],
    },
    intensity: 2,
    longevity: 2,
    tier: "advanced",
    priceRange: "¥200-400/50ml",
    description: "Fantasia 俏皮花果甜，少女入门首选",
  },
  "赤霞橘光": {
    id: "赤霞橘光",
    name: "赤霞橘光",
    brand: "Atelier Cologne",
    brandCn: "欧珑",
    notes: {
      top: ["橙","香橙","葡萄柚"],
      heart: ["茉莉","橙花"],
      base: ["檀香","麝香"],
    },
    intensity: 2,
    longevity: 2,
    tier: "advanced",
    priceRange: "¥500-800/30ml",
    description: "Orange Sanguine 血橙爆汁感，元气十足的柑橘调",
  },
  "沁蓝": {
    id: "沁蓝",
    name: "沁蓝",
    brand: "Atelier Cologne",
    brandCn: "欧珑",
    notes: {
      top: ["青柠","柠檬","佛手柑"],
      heart: ["橙叶","柠檬草"],
      base: ["雪松","麝香"],
    },
    intensity: 1,
    longevity: 1,
    tier: "advanced",
    priceRange: "¥500-800/30ml",
    description: "Cedrat Enivrant 清冽柠檬与佛手柑的极清爽",
  },
  "海盐柠檬": {
    id: "海盐柠檬",
    name: "海盐柠檬",
    brand: "Juliette Has A Gun",
    brandCn: "配枪朱丽叶",
    notes: {
      top: ["柠檬","青柠"],
      heart: ["海盐","玫瑰"],
      base: ["木质","麝香"],
    },
    intensity: 2,
    longevity: 2,
    tier: "advanced",
    priceRange: "¥600-900/50ml",
    description: "清冷柠檬海盐，清凉松弛的日常好搭",
  },
  "格调": {
    id: "格调",
    name: "格调",
    brand: "Acqua di Parma",
    brandCn: "帕尔玛之水",
    notes: {
      top: ["柠檬","佛手柑","香橙"],
      heart: ["迷迭香","薰衣草"],
      base: ["雪松","檀香","琥珀"],
    },
    intensity: 2,
    longevity: 2,
    tier: "advanced",
    priceRange: "¥800-1300/50ml",
    description: "Colonia 百年经典古龙水，意大利绅士的优雅柑橘调",
  },
  "西柚天堂": {
    id: "西柚天堂",
    name: "西柚天堂",
    brand: "Atelier Cologne",
    brandCn: "欧珑",
    notes: {
      top: ["葡萄柚","香橙","柠檬"],
      heart: ["薄荷","橙花"],
      base: ["香根草","麝香"],
    },
    intensity: 1,
    longevity: 1,
    tier: "advanced",
    priceRange: "¥500-800/30ml",
    description: "Pomelo Paradis 葡萄柚的清爽微苦，夏日最提神",
  },
  "红结晶": {
    id: "红结晶",
    name: "红结晶",
    brand: "Maison Francis Kurkdjian",
    brandCn: "MFK",
    notes: {
      top: ["藏红花","茉莉"],
      heart: ["琥珀","雪松"],
      base: ["树脂","麝香"],
    },
    intensity: 3,
    longevity: 4,
    tier: "signature",
    priceRange: "¥1800-2500/70ml",
    description: "Baccarat Rouge 540 藏红花琥珀的冰糖葫芦香，仙气又致瘾",
  },
  "不朽之花": {
    id: "不朽之花",
    name: "不朽之花",
    brand: "Byredo",
    brandCn: "百瑞德",
    notes: {
      top: ["橙","柠檬"],
      heart: ["茉莉","百合"],
      base: ["檀木","琥珀"],
    },
    intensity: 2,
    longevity: 2,
    tier: "signature",
    priceRange: "¥1200-1600/50ml",
    description: "Inflorescence 清新白花与柑橘的优雅交织",
  },
  "香柠檬": {
    id: "香柠檬",
    name: "香柠檬",
    brand: "Jo Malone",
    brandCn: "祖玛珑",
    notes: {
      top: ["佛手柑","柠檬"],
      heart: ["橙花","玫瑰"],
      base: ["雪松","麝香"],
    },
    intensity: 1,
    longevity: 1,
    tier: "advanced",
    priceRange: "¥500-800/30ml",
    description: "清新佛手柑搭配橙花，干净的通勤香",
  },
  "自由之水": {
    id: "自由之水",
    name: "自由之水",
    brand: "Floraku",
    brandCn: "佛罗伊库",
    notes: {
      top: ["黑醋栗叶","青柠"],
      heart: ["玫瑰","桂花"],
      base: ["木质","麝香"],
    },
    intensity: 2,
    longevity: 3,
    tier: "signature",
    priceRange: "¥1200-1800/50ml",
    description: "清冷绿意桂花玫瑰，高级感的小众文艺香",
  },

  // ══ YSL 高定线 (Le Vestiaire des Parfums) ══
  燕尾服: {
    id: "燕尾服",
    name: "燕尾服",
    brand: "YSL",
    brandCn: "圣罗兰",
    notes: {
      top: ["粉红胡椒", "紫罗兰叶"],
      heart: ["广藿香", "琥珀"],
      base: ["皮革", "焚香"],
    },
    intensity: 4,
    longevity: 5,
    tier: "signature",
    priceRange: "¥2200-2800/50ml",
    description: "燕尾服的优雅，夜间社交的完美签名。",
  },
  羊毛大衣: {
    id: "羊毛大衣",
    name: "羊毛大衣",
    brand: "YSL",
    brandCn: "圣罗兰",
    notes: {
      top: ["粉红胡椒", "乳香"],
      heart: ["焚香", "木质"],
      base: ["檀香", "琥珀"],
    },
    intensity: 4,
    longevity: 5,
    tier: "signature",
    priceRange: "¥2200-2800/50ml",
    description: "羊毛大衣里的温度，深夜码头的气场。",
  },
  丝绸衬衫: {
    id: "丝绸衬衫",
    name: "丝绸衬衫",
    brand: "YSL",
    brandCn: "圣罗兰",
    notes: {
      top: ["粉红胡椒", "佛手柑"],
      heart: ["大马士革玫瑰", "白麝香"],
      base: ["绒面", "安息香"],
    },
    intensity: 3,
    longevity: 4,
    tier: "signature",
    priceRange: "¥2200-2800/50ml",
    description: "丝绸衬衫的触感，柔软而锋利。",
  },

  // ══ Guerlain 艺术沙龙线 (L'Art & La Matière) ══
  朗姆香草: {
    id: "朗姆香草",
    name: "朗姆香草",
    brand: "Guerlain",
    brandCn: "娇兰",
    notes: {
      top: ["佛手柑", "朗姆酒"],
      heart: ["香草", "雪松"],
      base: ["焚香", "胡椒", "琥珀"],
    },
    intensity: 4,
    longevity: 5,
    tier: "signature",
    priceRange: "¥2000-2600/50ml",
    description: "朗姆酒浸香草，时间酿出的灵魂香气。",
  },
  白鲸皮: {
    id: "白鲸皮",
    name: "白鲸皮",
    brand: "Guerlain",
    brandCn: "娇兰",
    notes: {
      top: ["醛类", "天芥菜"],
      heart: ["皮革", "琥珀"],
      base: ["香草", "白麝香", "苏合香"],
    },
    intensity: 3,
    longevity: 5,
    tier: "signature",
    priceRange: "¥2000-2600/50ml",
    description: "白鲸皮的柔韧，拥抱中的温度。",
  },
  暗黑天使: {
    id: "暗黑天使",
    name: "暗黑天使",
    brand: "Guerlain",
    brandCn: "娇兰",
    notes: {
      top: ["佛手柑", "粉红胡椒"],
      heart: ["当归", "茉莉"],
      base: ["香草", "雪松", "鸢尾根"],
    },
    intensity: 3,
    longevity: 4,
    tier: "signature",
    priceRange: "¥2000-2600/50ml",
    description: "暗黑天使，苦涩中的甜美觉醒。",
  },

  // ══ Dior 高定线 (La Collection Privée) ══
  银林: {
    id: "银林",
    name: "银林",
    brand: "Dior",
    brandCn: "迪奥",
    notes: {
      top: ["粉红胡椒", "杜松子"],
      heart: ["鸢尾", "白麝香"],
      base: ["蜂蜜", "木质"],
    },
    intensity: 3,
    longevity: 5,
    tier: "signature",
    priceRange: "¥1800-2400/50ml",
    description: "流动的银，纸与墨之间的冥想。",
  },
  深夜琥珀: {
    id: "深夜琥珀",
    name: "深夜琥珀",
    brand: "Dior",
    brandCn: "迪奥",
    notes: {
      top: ["粉红胡椒", "佛手柑"],
      heart: ["大马士革玫瑰", "琥珀"],
      base: ["广藿香", "龙涎香", "愈创木"],
    },
    intensity: 4,
    longevity: 5,
    tier: "signature",
    priceRange: "¥1800-2400/50ml",
    description: "深夜琥珀，玫瑰在暗处燃烧的温度。",
  },
  灰色优雅: {
    id: "灰色优雅",
    name: "灰色优雅",
    brand: "Dior",
    brandCn: "迪奥",
    notes: {
      top: ["佛手柑", "香柠檬"],
      heart: ["橡木苔", "大马士革玫瑰"],
      base: ["广藿香", "雪松", "檀香"],
    },
    intensity: 3,
    longevity: 4,
    tier: "signature",
    priceRange: "¥1800-2400/50ml",
    description: "灰色的优雅，知识分子香。",
  },

  // ══ Kilian 标志款 ══
  直达天堂: {
    id: "直达天堂",
    name: "直达天堂",
    brand: "Kilian",
    brandCn: "凯利安",
    notes: {
      top: ["朗姆酒", "黑胡椒"],
      heart: ["丝柏", "广藿香"],
      base: ["雪松", "干琥珀", "零陵香豆"],
    },
    intensity: 5,
    longevity: 5,
    tier: "signature",
    priceRange: "¥2000-2600/50ml",
    description: "一口朗姆烈酒，直达天堂的木质沉醉。",
  },
  月光天堂: {
    id: "月光天堂",
    name: "月光天堂",
    brand: "Kilian",
    brandCn: "凯利安",
    notes: {
      top: ["芒果", "香柠檬"],
      heart: ["茉莉", "大米"],
      base: ["椰子", "岩兰草"],
    },
    intensity: 3,
    longevity: 4,
    tier: "signature",
    priceRange: "¥2000-2600/50ml",
    description: "月光下的东南亚天堂，果香与米饭的温暖。",
  },
  天使之享: {
    id: "天使之享",
    name: "天使之享",
    brand: "Kilian",
    brandCn: "凯利安",
    notes: {
      top: ["干邑白兰地", "肉桂"],
      heart: ["橡木", "零陵香豆"],
      base: ["香草", "檀香", "杏仁"],
    },
    intensity: 4,
    longevity: 5,
    tier: "signature",
    priceRange: "¥2200-2800/50ml",
    description: "天使洒落的干邑，橡木桶里藏着的最深的甜。",
  },

  // ══ 国内中高端 ══
  // ── 观夏 (To Summer) ──
  昆仑煮雪: {
    id: "昆仑煮雪",
    name: "昆仑煮雪",
    brand: "观夏",
    brandCn: "观夏",
    notes: {
      top: ["松针", "香柠檬"],
      heart: ["杜松子", "雪松"],
      base: ["焚香", "琥珀", "愈创木"],
    },
    intensity: 3,
    longevity: 4,
    tier: "signature",
    priceRange: "¥498/30ml",
    description: "昆仑山巅的松雪，焚一支香，煮一壶茶的东方意境。",
  },
  三重茶: {
    id: "三重茶",
    name: "三重茶",
    brand: "观夏",
    brandCn: "观夏",
    notes: {
      top: ["佛手柑", "薄荷"],
      heart: ["绿茶", "烟草", "茉莉"],
      base: ["岩兰草", "愈创木"],
    },
    intensity: 2,
    longevity: 3,
    tier: "signature",
    priceRange: "¥498/30ml",
    description: "一壶茶的三重味道——清香、微苦、回甘。",
  },
  颐和金桂: {
    id: "颐和金桂",
    name: "颐和金桂",
    brand: "观夏",
    brandCn: "观夏",
    notes: {
      top: ["杏", "佛手柑"],
      heart: ["桂花", "白茶"],
      base: ["檀香", "麝香"],
    },
    intensity: 2,
    longevity: 3,
    tier: "signature",
    priceRange: "¥498/30ml",
    description: "颐和园的金桂落在青石板上，秋风里的甜。",
  },

  // ── 闻献 (DOCUMENTS) ──
  初熟之物: {
    id: "初熟之物",
    name: "初熟之物",
    brand: "闻献",
    brandCn: "闻献",
    notes: {
      top: ["桃子", "青柠"],
      heart: ["黄瓜", "天竺葵"],
      base: ["绿茶", "麝香"],
    },
    intensity: 2,
    longevity: 3,
    tier: "signature",
    priceRange: "¥980/30ml",
    description: "桃子刚熟的那一刻，青涩与甜蜜的交界。",
  },
  柔韧荆棘: {
    id: "柔韧荆棘",
    name: "柔韧荆棘",
    brand: "闻献",
    brandCn: "闻献",
    notes: {
      top: ["胡椒", "佛手柑"],
      heart: ["大马士革玫瑰", "焚香"],
      base: ["广藿香", "皮革"],
    },
    intensity: 4,
    longevity: 4,
    tier: "signature",
    priceRange: "¥980/30ml",
    description: "荆棘丛中的玫瑰，柔软而锋利。",
  },
  夜漠回声: {
    id: "夜漠回声",
    name: "夜漠回声",
    brand: "闻献",
    brandCn: "闻献",
    notes: {
      top: ["小豆蔻", "藏红花"],
      heart: ["皮革", "檀香"],
      base: ["琥珀", "沉香", "麝香"],
    },
    intensity: 4,
    longevity: 5,
    tier: "signature",
    priceRange: "¥980/30ml",
    description: "深夜沙漠的风，带回来的远方回声。",
  },

  // ── 浮香堂 ──
  墨: {
    id: "墨",
    name: "墨",
    brand: "浮香堂",
    brandCn: "浮香堂",
    notes: {
      top: ["柑橘", "粉红胡椒"],
      heart: ["纸莎草", "鸢尾"],
      base: ["檀香", "麝香", "雪松"],
    },
    intensity: 2,
    longevity: 3,
    tier: "signature",
    priceRange: "¥488/30ml",
    description: "研墨时第一缕松烟，文人书斋的气味记忆。",
  },
  桂: {
    id: "桂",
    name: "桂",
    brand: "浮香堂",
    brandCn: "浮香堂",
    notes: {
      top: ["柑橘", "杏"],
      heart: ["桂花", "白茶", "茉莉"],
      base: ["麝香", "鸢尾根"],
    },
    intensity: 2,
    longevity: 3,
    tier: "signature",
    priceRange: "¥488/30ml",
    description: "雨后巷口的老桂树，中国式的清甜。",
  },

  // ══ 平价池扩充（路径B：增厚 budget 池，从根源降低跨原型撞车）══
  // 覆盖 6 个香调家族，notes 关键词均取自 INGREDIENT_MAP，确保算法能正确推导向量。
  "玫瑰初语": {
    id: "玫瑰初语",
    name: "玫瑰初语",
    brand: "Zara",
    brandCn: "飒拉",
    notes: { top: ["玫瑰"], heart: ["牡丹", "茉莉"], base: ["麝香"] },
    intensity: 3, longevity: 3,
    tier: "budget",
    priceRange: "¥150-300/50ml",
    description: "清甜玫瑰叠牡丹，平价入门的花香。",
  },
  "白茉莉": {
    id: "白茉莉",
    name: "白茉莉",
    brand: "网易严选",
    brandCn: "网易严选",
    notes: { top: ["茉莉"], heart: ["铃兰"], base: ["木质"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥100-200/50ml",
    description: "干净白花，茉莉与铃兰的清淡少女感。",
  },
  "紫罗兰心事": {
    id: "紫罗兰心事",
    name: "紫罗兰心事",
    brand: "Boitown",
    brandCn: "冰希黎",
    notes: { top: ["紫罗兰"], heart: ["鸢尾"], base: ["麝香"] },
    intensity: 2, longevity: 3,
    tier: "budget",
    priceRange: "¥120-260/50ml",
    description: "粉感紫罗兰与鸢尾，温柔内向的花粉香。",
  },
  "桂花引": {
    id: "桂花引",
    name: "桂花引",
    brand: "MINISO",
    brandCn: "名创优品",
    notes: { top: ["桂花"], heart: ["白茶"], base: ["木质"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥80-180/50ml",
    description: "清甜桂花配白茶，东方清润的平价茶花香。",
  },
  "檀木序曲": {
    id: "檀木序曲",
    name: "檀木序曲",
    brand: "和风雨",
    brandCn: "和风雨",
    notes: { top: ["檀香"], heart: ["雪松"], base: ["广藿香"] },
    intensity: 3, longevity: 4,
    tier: "budget",
    priceRange: "¥120-240/50ml",
    description: "温润檀木与雪松，沉稳木质的日常香。",
  },
  "雪松荒野": {
    id: "雪松荒野",
    name: "雪松荒野",
    brand: "Zara",
    brandCn: "飒拉",
    notes: { top: ["雪松"], heart: ["香根草"], base: ["琥珀"] },
    intensity: 3, longevity: 4,
    tier: "budget",
    priceRange: "¥150-300/50ml",
    description: "干燥雪松与香根草，荒野木质调。",
  },
  "岩兰物语": {
    id: "岩兰物语",
    name: "岩兰物语",
    brand: "Boitown",
    brandCn: "冰希黎",
    notes: { top: ["岩兰草"], heart: ["柏木"], base: ["木质"] },
    intensity: 3, longevity: 4,
    tier: "budget",
    priceRange: "¥120-260/50ml",
    description: "泥土感岩兰草与柏木，低调耐闻的木质。",
  },
  "海盐微光": {
    id: "海盐微光",
    name: "海盐微光",
    brand: "Zara",
    brandCn: "飒拉",
    notes: { top: ["海盐", "薄荷"], heart: ["海洋"], base: ["麝香"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥150-300/50ml",
    description: "海盐与薄荷的水感，夏日清爽便宜大碗。",
  },
  "雨后青苔": {
    id: "雨后青苔",
    name: "雨后青苔",
    brand: "气味图书馆",
    brandCn: "气味图书馆",
    notes: { top: ["青苔"], heart: ["绿叶"], base: ["苔藓"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥100-200/50ml",
    description: "雨后被踩过的青苔与绿叶，森系清新。",
  },
  "无花果奶冻": {
    id: "无花果奶冻",
    name: "无花果奶冻",
    brand: "MINISO",
    brandCn: "名创优品",
    notes: { top: ["无花果"], heart: ["椰"], base: ["木质"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥80-180/50ml",
    description: "奶感无花果配椰香，清新又带点甜。",
  },
  "绿茶醒": {
    id: "绿茶醒",
    name: "绿茶醒",
    brand: "茶里",
    brandCn: "茶里",
    notes: { top: ["茶叶", "柠檬"], heart: ["薄荷"], base: ["木质"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥100-200/50ml",
    description: "绿茶与柠檬薄荷，醒神又干净的茶香。",
  },
  "琥珀夜行": {
    id: "琥珀夜行",
    name: "琥珀夜行",
    brand: "Boitown",
    brandCn: "冰希黎",
    notes: { top: ["琥珀"], heart: ["香草"], base: ["麝香"] },
    intensity: 3, longevity: 4,
    tier: "budget",
    priceRange: "¥120-260/50ml",
    description: "暖琥珀裹香草与麝香，平价版慵懒东方调。",
  },
  "沉香迷雾": {
    id: "沉香迷雾",
    name: "沉香迷雾",
    brand: "和风雨",
    brandCn: "和风雨",
    notes: { top: ["沉香"], heart: ["檀香"], base: ["皮革"] },
    intensity: 4, longevity: 5,
    tier: "budget",
    priceRange: "¥130-280/50ml",
    description: "沉香与皮革的烟熏感，暗黑有故事的平价香。",
  },
  "焚香结界": {
    id: "焚香结界",
    name: "焚香结界",
    brand: "Zara",
    brandCn: "飒拉",
    notes: { top: ["焚香"], heart: ["雪松"], base: ["檀香"] },
    intensity: 3, longevity: 4,
    tier: "budget",
    priceRange: "¥150-300/50ml",
    description: "寺庙焚香与木质的清冷禁欲感。",
  },
  "香橙假日": {
    id: "香橙假日",
    name: "香橙假日",
    brand: "Zara",
    brandCn: "飒拉",
    notes: { top: ["香橙", "柠檬"], heart: ["佛手柑"], base: ["木质"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥150-300/50ml",
    description: "一整颗香橙的明亮，元气柑橘入门香。",
  },
  "柚子少年": {
    id: "柚子少年",
    name: "柚子少年",
    brand: "MINISO",
    brandCn: "名创优品",
    notes: { top: ["柚子", "葡萄柚"], heart: ["薄荷"], base: ["木质"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥80-180/50ml",
    description: "柚子与葡萄柚的酸爽，少年感的清爽。",
  },
  "青柠气泡": {
    id: "青柠气泡",
    name: "青柠气泡",
    brand: "网易严选",
    brandCn: "网易严选",
    notes: { top: ["青柠", "柠檬草"], heart: ["海盐"], base: ["木质"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥100-200/50ml",
    description: "青柠气泡水般的清凉，夏日提神平价香。",
  },
  "香草奶昔": {
    id: "香草奶昔",
    name: "香草奶昔",
    brand: "Zara",
    brandCn: "飒拉",
    notes: { top: ["香草"], heart: ["牛奶"], base: ["椰子"] },
    intensity: 3, longevity: 3,
    tier: "budget",
    priceRange: "¥150-300/50ml",
    description: "香草牛奶冰淇淋，甜而不腻的平价奶香。",
  },
  "焦糖布蕾": {
    id: "焦糖布蕾",
    name: "焦糖布蕾",
    brand: "Boitown",
    brandCn: "冰希黎",
    notes: { top: ["焦糖"], heart: ["奶油"], base: ["杏仁"] },
    intensity: 3, longevity: 3,
    tier: "budget",
    priceRange: "¥120-260/50ml",
    description: "焦糖与奶油的甜点香，平价版的甜暖。",
  },
  "蜜桃软糖": {
    id: "蜜桃软糖",
    name: "蜜桃软糖",
    brand: "MINISO",
    brandCn: "名创优品",
    notes: { top: ["桃子"], heart: ["糖"], base: ["莓果"] },
    intensity: 3, longevity: 3,
    tier: "budget",
    priceRange: "¥80-180/50ml",
    description: "水蜜桃软糖，少女感果香平价香。",
  },
  "棉花糖星河": {
    id: "棉花糖星河",
    name: "棉花糖星河",
    brand: "气味图书馆",
    brandCn: "气味图书馆",
    notes: { top: ["棉花糖"], heart: ["香草"], base: ["麝香"] },
    intensity: 3, longevity: 3,
    tier: "budget",
    priceRange: "¥100-200/50ml",
    description: "蓬松棉花糖与香草，甜梦般的平价香。",
  },

  // ════════════════════════════════════════════════════
  // 新增 55 支香水 (13 signature + 20 advanced + 22 budget)
  // ════════════════════════════════════════════════════

  // ── 新增 signature (13支) ──
  银色山泉: {
    id: "银色山泉",
    name: "银色山泉",
    brand: "Creed",
    brandCn: "信仰",
    notes: { top: ["香柠檬", "橙"], heart: ["茶", "黑醋栗"], base: ["麝香", "檀香", "苦艾"] },
    intensity: 3, longevity: 4,
    tier: "signature",
    priceRange: "¥1200-1800/50ml",
    description: "阿尔卑斯冰川融水般的纯净清冽，绅士标配。",
  },
  拿破仑之水: {
    id: "拿破仑之水",
    name: "拿破仑之水",
    brand: "Creed",
    brandCn: "信仰",
    notes: { top: ["菠萝", "黑醋栗", "苹果"], heart: ["桦木", "玫瑰", "茉莉"], base: ["麝香", "琥珀", "橡木苔"] },
    intensity: 4, longevity: 5,
    tier: "signature",
    priceRange: "¥1500-2200/50ml",
    description: "水果与烟熏木质的王座，气场炸裂的霸总香。",
  },
  珍珠乌木: {
    id: "珍珠乌木",
    name: "珍珠乌木",
    brand: "Tom Ford",
    brandCn: "汤姆·福特",
    notes: { top: ["香柠檬", "小豆蔻"], heart: ["玫瑰", "覆盆子"], base: ["沉香木", "檀香", "香草"] },
    intensity: 4, longevity: 5,
    tier: "signature",
    priceRange: "¥2500-3500/50ml",
    description: "玫瑰覆盆子与乌木的奢华碰撞，私藏系列巅峰。",
  },
  皇家沉香: {
    id: "皇家沉香",
    name: "皇家沉香",
    brand: "Roja Parfums",
    brandCn: "罗嘉",
    notes: { top: ["香柠檬", "柠檬"], heart: ["玫瑰", "茉莉", "沉香"], base: ["琥珀", "麝香", "檀香"] },
    intensity: 4, longevity: 5,
    tier: "signature",
    priceRange: "¥2500-4000/50ml",
    description: "英伦高定的极致奢华，沉香玫瑰的皇家仪式感。",
  },
  红色国王: {
    id: "红色国王",
    name: "红色国王",
    brand: "Xerjoff",
    brandCn: "赛尔乔夫",
    notes: { top: ["香柠檬", "肉桂"], heart: ["玫瑰", "广藿香"], base: ["琥珀", "沉香", "麝香"] },
    intensity: 4, longevity: 5,
    tier: "signature",
    priceRange: "¥2000-3000/50ml",
    description: "意大利匠人精神的极致，玫瑰琥珀的贵族气场。",
  },
  "镜中": {
    id: "镜中",
    name: "镜中",
    brand: "Amouage",
    brandCn: "爱慕",
    notes: { top: ["乳香", "牛至"], heart: ["琥珀", "没药", "劳丹脂"], base: ["檀香", "沉香", "麝香"] },
    intensity: 5, longevity: 5,
    tier: "signature",
    priceRange: "¥1800-2600/50ml",
    description: "阿曼皇室的奢华仪式，乳香琥珀的混沌之美。",
  },
  百家乐红540: {
    id: "百家乐红540",
    name: "百家乐红540",
    brand: "Maison Francis Kurkdjian",
    brandCn: "MFK",
    notes: { top: ["藏红花", "茉莉"], heart: ["琥珀", "雪松"], base: ["树脂", "麝香"] },
    intensity: 3, longevity: 5,
    tier: "signature",
    priceRange: "¥1800-2500/70ml",
    description: "藏红花琥珀的仙气甜香，最火沙龙香之一。",
  },
  肌肤之亲: {
    id: "肌肤之亲",
    name: "肌肤之亲",
    brand: "Frederic Malle",
    brandCn: "馥马尔",
    notes: { top: ["醛类", "香柠檬"], heart: ["玫瑰", "鸢尾"], base: ["麝香", "蜂蜜", "檀香"] },
    intensity: 3, longevity: 4,
    tier: "signature",
    priceRange: "¥1500-2200/50ml",
    description: "醛香玫瑰与蜂蜜麝香，亲密无间的肌肤感。",
  },
  原始动力: {
    id: "原始动力",
    name: "原始动力",
    brand: "Initio",
    brandCn: "因尼提奥",
    notes: { top: ["香柠檬", "薰衣草"], heart: ["檀香", "鼠尾草"], base: ["皮革", "麝香"] },
    intensity: 4, longevity: 5,
    tier: "signature",
    priceRange: "¥1800-2600/50ml",
    description: "纯净檀香与皮革的狂野，磁场全开的派对香。",
  },
  莱伊: {
    id: "莱伊",
    name: "莱伊",
    brand: "Parfums de Marly",
    brandCn: "玛丽之香",
    notes: { top: ["香柠檬", "薰衣草"], heart: ["天竺葵", "玫瑰"], base: ["檀香", "香根草", "麝香"] },
    intensity: 3, longevity: 4,
    tier: "signature",
    priceRange: "¥1200-1800/50ml",
    description: "法式宫廷优雅，薰衣草天竺葵的精致均衡。",
  },
  木兰乱染: {
    id: "木兰乱染",
    name: "木兰乱染",
    brand: "Marc-Antoine Barrois",
    brandCn: "马克·安托万·巴鲁瓦",
    notes: { top: ["香柠檬", "菠萝"], heart: ["薰衣草", "天竺葵"], base: ["香根草", "雪松", "麝香"] },
    intensity: 3, longevity: 5,
    tier: "signature",
    priceRange: "¥1200-1800/50ml",
    description: "丝绒般的花粉感与木质，文艺小众的法国新贵。",
  },
  另一种乌木: {
    id: "另一种乌木",
    name: "另一种乌木",
    brand: "Le Labo",
    brandCn: "勒拉博",
    notes: { top: ["小豆蔻", "香柠檬"], heart: ["沉香", "玫瑰"], base: ["檀香", "麝香"] },
    intensity: 3, longevity: 5,
    tier: "signature",
    priceRange: "¥1400-2000/50ml",
    description: "沉香玫瑰与小豆蔻，极简实验室的东方木香。",
  },
  黑檀木与红木: {
    id: "黑檀木与红木",
    name: "黑檀木与红木",
    brand: "Tom Ford",
    brandCn: "汤姆·福特",
    notes: { top: ["花椒", "香柠檬"], heart: ["雪松", "马黛茶"], base: ["檀香", "沉香", "香根草"] },
    intensity: 3, longevity: 5,
    tier: "signature",
    priceRange: "¥2200-3200/50ml",
    description: "花椒与马黛茶的异域木香，克制中的深梣。",
  },

  // ── 新增 advanced (20支) ──
  伦敦无花果: {
    id: "伦敦无花果",
    name: "伦敦无花果",
    brand: "Jo Malone",
    brandCn: "祖玛珑",
    notes: { top: ["无花果", "香柠檬"], heart: ["无花果叶", "椰子"], base: ["雪松", "檀香"] },
    intensity: 2, longevity: 3,
    tier: "advanced",
    priceRange: "¥500-800/30ml",
    description: "英伦花园的无花果树，奶绿交织的清新日常。",
  },
  牡丹与胭红麂绒: {
    id: "牡丹与胭红麂绒",
    name: "牡丹与胭红麂绒",
    brand: "Jo Malone",
    brandCn: "祖玛珑",
    notes: { top: ["苹果"], heart: ["牡丹", "玫瑰"], base: ["麂绒", "麝香"] },
    intensity: 3, longevity: 3,
    tier: "advanced",
    priceRange: "¥500-800/30ml",
    description: "苹果牡丹与麂绒，高级感满满的花香新贵。",
  },
  香根草: {
    id: "香根草",
    name: "香根草",
    brand: "Jo Malone",
    brandCn: "祖玛珑",
    notes: { top: ["香柠檬", "橙"], heart: ["香根草", "鼠尾草"], base: ["檀香", "麝香"] },
    intensity: 3, longevity: 3,
    tier: "advanced",
    priceRange: "¥500-800/30ml",
    description: "根茎类香草的泥土清苦，文艺复兴的草本香。",
  },
  茉莉与烟草: {
    id: "茉莉与烟草",
    name: "茉莉与烟草",
    brand: "Jo Malone",
    brandCn: "祖玛珑",
    notes: { top: ["香柠檬", "橙"], heart: ["茉莉", "烟草"], base: ["麝香", "木质"] },
    intensity: 2, longevity: 3,
    tier: "advanced",
    priceRange: "¥500-800/30ml",
    description: "茉莉花与烟叶的意外和谐，优雅又带点不羁。",
  },
  檀木25: {
    id: "檀木25",
    name: "檀木25",
    brand: "Le Labo",
    brandCn: "勒拉博",
    notes: { top: ["橙", "香柠檬"], heart: ["檀香", "鸢尾"], base: ["麝香", "香根草"] },
    intensity: 3, longevity: 4,
    tier: "signature",
    priceRange: "¥1400-2000/50ml",
    description: "纽约城市限定檀香，温润木香与橙花交织。",
  },
  感官之水: {
    id: "感官之水",
    name: "感官之水",
    brand: "Diptyque",
    brandCn: "蒂普提克",
    notes: { top: ["香柠檬", "橙花"], heart: ["橙花", "茉莉"], base: ["麝香", "木质"] },
    intensity: 2, longevity: 3,
    tier: "advanced",
    priceRange: "¥700-1100/50ml",
    description: "橙花茉莉的纯净白花，Eau des Sens 感官之水。",
  },
  罗斯柑橘: {
    id: "罗斯柑橘",
    name: "罗斯柑橘",
    brand: "Acqua di Parma",
    brandCn: "帕尔玛之水",
    notes: { top: ["香橙", "柠檬", "柑橘"], heart: ["橙花", "玫瑰"], base: ["雪松", "麝香"] },
    intensity: 2, longevity: 2,
    tier: "advanced",
    priceRange: "¥500-800/50ml",
    description: "意大利南部的阳光柑橘与玫瑰，清晣不失优雅。",
  },
  卡普里岛香橙: {
    id: "卡普里岛香橙",
    name: "卡普里岛香橙",
    brand: "Acqua di Parma",
    brandCn: "帕尔玛之水",
    notes: { top: ["香橙", "柠檬", "橘子"], heart: ["橙花"], base: ["麝香", "雪松"] },
    intensity: 2, longevity: 2,
    tier: "advanced",
    priceRange: "¥500-800/50ml",
    description: "卡普里岛阳光下的香橙，地中海假日气息。",
  },
  印度香根草: {
    id: "印度香根草",
    name: "印度香根草",
    brand: "Hermes",
    brandCn: "爱马仕",
    notes: { top: ["香柠檬", "橙"], heart: ["香根草", "胡椒"], base: ["檀香", "麝香"] },
    intensity: 3, longevity: 4,
    tier: "advanced",
    priceRange: "¥600-900/100ml",
    description: "爱马仕的根茎美学，香根草的烟熏与泥土感。",
  },
  尼罗河花园: {
    id: "尼罗河花园",
    name: "尼罗河花园",
    brand: "Hermes",
    brandCn: "爱马仕",
    notes: { top: ["葡萄柚", "香橙"], heart: ["莲花", "风信子"], base: ["木质", "乳香"] },
    intensity: 2, longevity: 3,
    tier: "advanced",
    priceRange: "¥600-900/50ml",
    description: "尼罗河畔的青芒果与莲花，清透水生花园。",
  },
  爱马仕之旅: {
    id: "爱马仕之旅",
    name: "爱马仕之旅",
    brand: "Hermes",
    brandCn: "爱马仕",
    notes: { top: ["香柠檬", "橙"], heart: ["茶叶", "桂花"], base: ["木质", "麝香"] },
    intensity: 3, longevity: 3,
    tier: "advanced",
    priceRange: "¥600-900/100ml",
    description: "茶桂与木质的温和均衡，低调的东方叙事。",
  },
  五号之水: {
    id: "五号之水",
    name: "五号之水",
    brand: "Chanel",
    brandCn: "香奈儿",
    notes: { top: ["柠檬", "橙"], heart: ["玫瑰", "茉莉", "鸢尾"], base: ["麝香", "雪松", "香草"] },
    intensity: 2, longevity: 3,
    tier: "advanced",
    priceRange: "¥800-1200/50ml",
    description: "五号的年轻版本，醛香花女的温柔日常。",
  },
  邂逅柔情: {
    id: "邂逅柔情",
    name: "邂逅柔情",
    brand: "Chanel",
    brandCn: "香奈儿",
    notes: { top: ["香柠檬", "柠檬"], heart: ["茉莉", "玫瑰"], base: ["麝香", "雪松"] },
    intensity: 2, longevity: 3,
    tier: "advanced",
    priceRange: "¥800-1200/50ml",
    description: "Chance Eau Tendre 的少女花香，温柔不挑人。",
  },
  花草水语柑橘: {
    id: "花草水语柑橘",
    name: "花草水语柑橘",
    brand: "Guerlain",
    brandCn: "娇兰",
    notes: { top: ["香柠檬", "柠檬"], heart: ["橙花", "薰衣草"], base: ["麝香", "檀香"] },
    intensity: 2, longevity: 2,
    tier: "advanced",
    priceRange: "¥600-900/50ml",
    description: "阳光下的普罗旺斯柑橘园，清淡优雅的日常香。",
  },
  小黑裙: {
    id: "小黑裙",
    name: "小黑裙",
    brand: "Guerlain",
    brandCn: "娇兰",
    notes: { top: ["玫瑰", "樱桃"], heart: ["玫瑰", "牡丹"], base: ["麝香", "檀香", "广藿香"] },
    intensity: 3, longevity: 4,
    tier: "advanced",
    priceRange: "¥600-900/50ml",
    description: "经典小黑裙的玫瑰樱桃，优雅法式女人香。",
  },
  花怜: {
    id: "花怜",
    name: "花怜",
    brand: "Penhaligon's",
    brandCn: "潘海利根",
    notes: { top: ["香柠檬", "橙花"], heart: ["玫瑰", "牡丹"], base: ["麝香", "檀香"] },
    intensity: 2, longevity: 3,
    tier: "signature",
    priceRange: "¥800-1200/50ml",
    description: "英伦贵族的玫瑰花园，柔美粉感的花香侍女。",
  },
  藤编: {
    id: "藤编",
    name: "藤编",
    brand: "L'Artisan Parfumeur",
    brandCn: "阿蒂仙",
    notes: { top: ["香柠檬", "橙"], heart: ["无花果", "茉莉"], base: ["檀香", "麝香"] },
    intensity: 2, longevity: 3,
    tier: "advanced",
    priceRange: "¥500-700/50ml",
    description: "普罗旺斯藤篮里的无花果与茉莉，阳光手编。",
  },
  满园玫瑰: {
    id: "满园玫瑰",
    name: "满园玫瑰",
    brand: "Jo Malone",
    brandCn: "祖玛珑",
    notes: { top: ["柠檬", "薄荷"], heart: ["玫瑰", "紫罗兰"], base: ["麝香", "檀香"] },
    intensity: 2, longevity: 3,
    tier: "advanced",
    priceRange: "¥500-800/30ml",
    description: "清晨玫瑰园的薄荷叶与露珠，清新不做作。",
  },
  黑莓与月桂叶: {
    id: "黑莓与月桂叶",
    name: "黑莓与月桂叶",
    brand: "Jo Malone",
    brandCn: "祖玛珑",
    notes: { top: ["黑莓", "葡萄柚"], heart: ["月桂叶", "茉莉"], base: ["雪松", "麝香"] },
    intensity: 2, longevity: 3,
    tier: "advanced",
    priceRange: "¥500-800/30ml",
    description: "黑莓果香与月桂叶的草本清新，文艺日常。",
  },
  香根草仙踪: {
    id: "香根草仙踪",
    name: "香根草仙踪",
    brand: "Tom Ford",
    brandCn: "汤姆·福特",
    notes: { top: ["香柠檬", "橙花"], heart: ["香根草", "天竺葵"], base: ["橡木苔", "麝香"] },
    intensity: 3, longevity: 4,
    tier: "signature",
    priceRange: "¥1200-1800/50ml",
    description: "香根草与橡木苔的绿意迷宫，签名线的经典。",
  },

  // ── 新增 budget (22支) ──
  香木恋: {
    id: "香木恋",
    name: "香木恋",
    brand: "Zara",
    brandCn: "飒拉",
    notes: { top: ["香柠檬", "橙"], heart: ["檀香", "雪松"], base: ["麝香", "琥珀"] },
    intensity: 3, longevity: 3,
    tier: "budget",
    priceRange: "¥150-300/50ml",
    description: "温润檀木与柑橘，平价版的日常木质香。",
  },
  甜橙密语: {
    id: "甜橙密语",
    name: "甜橙密语",
    brand: "Zara",
    brandCn: "飒拉",
    notes: { top: ["香橙", "橘子"], heart: ["茉莉", "橙花"], base: ["麝香"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥150-300/50ml",
    description: "一剥即开的甜橙，元气满满的平价柑橘。",
  },
  茉莉清晨: {
    id: "茉莉清晨",
    name: "茉莉清晨",
    brand: "MINISO",
    brandCn: "名创优品",
    notes: { top: ["茉莉", "柠檬"], heart: ["白花", "铃兰"], base: ["麝香", "木质"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥80-180/50ml",
    description: "清晨采摘的茉莉花束，干净纯白花香。",
  },
  玫瑰晨露: {
    id: "玫瑰晨露",
    name: "玫瑰晨露",
    brand: "MINISO",
    brandCn: "名创优品",
    notes: { top: ["玫瑰", "露水"], heart: ["牡丹"], base: ["麝香"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥80-180/50ml",
    description: "清晨玫瑰花瓣上的露珠，清新甜美的花蕾。",
  },
  蔚蓝海岸: {
    id: "蔚蓝海岸",
    name: "蔚蓝海岸",
    brand: "Zara",
    brandCn: "飒拉",
    notes: { top: ["海盐", "柠檬"], heart: ["海洋", "薰衣草"], base: ["麝香", "木质"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥150-300/50ml",
    description: "地中海海岸的咸湿海风，夏日水生平价香。",
  },
  白茶清墨: {
    id: "白茶清墨",
    name: "白茶清墨",
    brand: "Boitown",
    brandCn: "冰希黎",
    notes: { top: ["白茶", "香柠檬"], heart: ["茉莉", "橙花"], base: ["麝香", "木质"] },
    intensity: 2, longevity: 3,
    tier: "budget",
    priceRange: "¥120-260/50ml",
    description: "白茶与茉莉的安静香气，文艺青年的平价茶香。",
  },
  木质玫瑰: {
    id: "木质玫瑰",
    name: "木质玫瑰",
    brand: "Boitown",
    brandCn: "冰希黎",
    notes: { top: ["玫瑰", "粉红胡椒"], heart: ["玫瑰", "雪松"], base: ["麝香", "檀香"] },
    intensity: 3, longevity: 3,
    tier: "budget",
    priceRange: "¥120-260/50ml",
    description: "玫瑰与雪松的成熟组合，平价版的优雅女人香。",
  },
  青草薄荷: {
    id: "青草薄荷",
    name: "青草薄荷",
    brand: "气味图书馆",
    brandCn: "气味图书馆",
    notes: { top: ["薄荷", "青草"], heart: ["绿叶", "茶"], base: ["木质", "麝香"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥100-200/50ml",
    description: "刚修剪的草坪与薄荷，清新醒神的绿意。",
  },
  檀香奶盖: {
    id: "檀香奶盖",
    name: "檀香奶盖",
    brand: "和风雨",
    brandCn: "和风雨",
    notes: { top: ["檀香", "牛奶"], heart: ["椰子", "香草"], base: ["麝香", "琥珀"] },
    intensity: 3, longevity: 3,
    tier: "budget",
    priceRange: "¥120-240/50ml",
    description: "檀香与椰奶的温暖组合，平价版的拥抱香。",
  },
  柚子茶馆: {
    id: "柚子茶馆",
    name: "柚子茶馆",
    brand: "茶里",
    brandCn: "茶里",
    notes: { top: ["柚子", "柠檬"], heart: ["蜂蜜", "茶"], base: ["木质", "麝香"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥100-200/50ml",
    description: "蜂柚子茶的温暖甜香，秋冬里的暖意。",
  },
  海风微风: {
    id: "海风微风",
    name: "海风微风",
    brand: "网易严选",
    brandCn: "网易严选",
    notes: { top: ["海洋", "香柠檬"], heart: ["薰衣草", "鼠尾草"], base: ["麝香", "雪松"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥100-200/50ml",
    description: "海风拂面的清新水生香，干净日常不挑人。",
  },
  蔗糖玫瑰: {
    id: "蔗糖玫瑰",
    name: "蔗糖玫瑰",
    brand: "MINISO",
    brandCn: "名创优品",
    notes: { top: ["玫瑰", "糖"], heart: ["牡丹", "覆盆子"], base: ["麝香", "香草"] },
    intensity: 3, longevity: 3,
    tier: "budget",
    priceRange: "¥80-180/50ml",
    description: "糖裹玫瑰花瓣的甜香，少女心满溢的花果香。",
  },
  冷感橘皮: {
    id: "冷感橘皮",
    name: "冷感橘皮",
    brand: "Zara",
    brandCn: "飒拉",
    notes: { top: ["橘子", "薄荷"], heart: ["橙花", "茶叶"], base: ["麝香", "木质"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥150-300/50ml",
    description: "薄荷橘皮的清冷感，夏日清凉的平价选择。",
  },
  暖桃乌龙: {
    id: "暖桃乌龙",
    name: "暖桃乌龙",
    brand: "气味图书馆",
    brandCn: "气味图书馆",
    notes: { top: ["桃子", "茶"], heart: ["乌龙茶", "茉莉"], base: ["木质", "麝香"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥100-200/50ml",
    description: "蜜桃乌龙茶的清甜，午后茶馆般的舒适香。",
  },
  琥珀松林: {
    id: "琥珀松林",
    name: "琥珀松林",
    brand: "Boitown",
    brandCn: "冰希黎",
    notes: { top: ["松针", "香柠檬"], heart: ["雪松", "琥珀"], base: ["麝香", "檀香"] },
    intensity: 3, longevity: 4,
    tier: "budget",
    priceRange: "¥120-260/50ml",
    description: "松林深处的琥珀暖意，秋冬平价木质香。",
  },
  椰子语: {
    id: "椰子语",
    name: "椰子语",
    brand: "和风雨",
    brandCn: "和风雨",
    notes: { top: ["椰子", "香橙"], heart: ["茉莉", "椰奶"], base: ["麝香", "檀香"] },
    intensity: 2, longevity: 3,
    tier: "budget",
    priceRange: "¥120-240/50ml",
    description: "椰奶与热带花香的拥抱，平价假日的味道。",
  },
  森林松途: {
    id: "森林松途",
    name: "森林松途",
    brand: "Zara",
    brandCn: "飒拉",
    notes: { top: ["松针", "香柠檬"], heart: ["杜松子", "薰衣草"], base: ["雪松", "麝香"] },
    intensity: 3, longevity: 3,
    tier: "budget",
    priceRange: "¥150-300/50ml",
    description: "松林徒步的清冷空气，森系男孩的日常香。",
  },
  紫藤花语: {
    id: "紫藤花语",
    name: "紫藤花语",
    brand: "网易严选",
    brandCn: "网易严选",
    notes: { top: ["紫藤", "葡萄柚"], heart: ["牡丹", "铃兰"], base: ["麝香", "木质"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥100-200/50ml",
    description: "紫藤花架下的春日私语，温柔清新的白花香。",
  },
  青柠荒野: {
    id: "青柠荒野",
    name: "青柠荒野",
    brand: "MINISO",
    brandCn: "名创优品",
    notes: { top: ["青柠", "薄荷"], heart: ["鼠尾草", "海洋"], base: ["麝香", "木质"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥80-180/50ml",
    description: "青柠与鼠尾草的荒野清新，少年感夏日香。",
  },
  蜜藏琥珀: {
    id: "蜜藏琥珀",
    name: "蜜藏琥珀",
    brand: "Boitown",
    brandCn: "冰希黎",
    notes: { top: ["蜂蜜", "橙"], heart: ["琥珀", "劳丹脂"], base: ["麝香", "檀香"] },
    intensity: 3, longevity: 4,
    tier: "budget",
    priceRange: "¥120-260/50ml",
    description: "蜂蜜与琥珀的暖甜包裹，平价版的冬夜暖香。",
  },
  雪松薰衣草: {
    id: "雪松薰衣草",
    name: "雪松薰衣草",
    brand: "和风雨",
    brandCn: "和风雨",
    notes: { top: ["薰衣草", "香柠檬"], heart: ["雪松", "鼠尾草"], base: ["檀香", "麝香"] },
    intensity: 3, longevity: 3,
    tier: "budget",
    priceRange: "¥120-240/50ml",
    description: "薰衣草与雪松的宁静夜晚，安神助眠的木质草本。",
  },
  佛手柑伯爵茶: {
    id: "佛手柑伯爵茶",
    name: "佛手柑伯爵茶",
    brand: "茶里",
    brandCn: "茶里",
    notes: { top: ["佛手柑", "红茶"], heart: ["茉莉", "橙花"], base: ["木质", "麝香"] },
    intensity: 2, longevity: 2,
    tier: "budget",
    priceRange: "¥100-200/50ml",
    description: "伯爵茶与佛手柑的经典搭配，英式下午茶的优雅。",
  },
};
